### ISSUE TITLE
ulong values (bigger than int) can't be saved

### ISSUE THREAD

**Issue by digital-spinner** [influxdata/influxdb-client-csharp#149]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create the Point Value to be written with ulong value = ulong.MaxValue;
2. Try to save the point value using AsyncWrite.

__Expected behavior:__
Value should be written.

__Actual behavior:__
Exception occours:
```
InfluxDB.Client.Core.Exceptions.HttpException with message "unable to parse 'testMeasurementULong,tagName1=tagValue1 fieldNameULong=18446744073709551615i 1611569531282': unable to parse integer 18446744073709551615: strconv.ParseInt: parsing "18446744073709551615": value out of range"
     at InfluxDB.Client.Api.Service.WriteService.PostWriteAsyncWithIRestResponse(String org, String bucket, Byte[] body, String zapTraceSpan, String contentEncoding, String contentType, Nullable`1 contentLength, String accept, String orgID, Nullable`1 precision)
     at InfluxDB.Client.Api.Service.WriteService.PostWriteAsyncWithHttpInfo(String org, String bucket, Byte[] body, String zapTraceSpan, String contentEncoding, String contentType, Nullable`1 contentLength, String accept, String orgID, Nullable`1 precision)
     at InfluxDB.Client.Api.Service.WriteService.PostWriteAsync(String org, String bucket, Byte[] body, String zapTraceSpan, String contentEncoding, String contentType, Nullable`1 contentLength, String accept, String orgID, Nullable`1 precision)
     at InfluxDB.Client.WriteApiAsync.WriteData(String org, String bucket, WritePrecision precision, IEnumerable`1 data)
     at InfluxDB.Client.WriteApiAsync.WritePointsAsync(String bucket, String org, List`1 points)
     at InfluxDB.Client.WriteApiAsync.WritePointAsync(String bucket, String org, PointData point)
     at MHI.GCCP.TimeSeriesPersistence.ComponentTests.TimeSeriesPersistenceComponentTests.<>c__DisplayClass4_0.<<ShouldSuccessfullyWriteUnsignedLongPointData>b__0>d.MoveNext() in C:\Projects-MHIE\gccp-time-series-persistence-client\src\MHI.GCCP.TimeSeriesPersistence.ComponentTests\TimeSeriesPersistenceComponentTests.cs:line 151
  --- End of stack trace from previous location where exception was thrown ---
```

__Specifications:__
- Client Version: InfluxDB.Client 1.14.0
- InfluxDB Version: 2.0.3
- Platform: Linux Ubuntu 20.04

**Comment by bednar** [comment]
@digital-spinner, thanks for issue, we will take a look

**Comment by mklimczuk** [comment]
Hello together!
I think the problem is wrong converting to LineProtocol in PointData class.
`                else if (value is byte || value is int || value is long || value is sbyte || value is short ||
                         value is uint || value is ulong || value is ushort)
                {
                    sb.Append(((IConvertible)value).ToString(CultureInfo.InvariantCulture));
                    sb.Append('i');
                }`
https://github.com/influxdata/influxdb-client-csharp/blob/0272fa3437cf3d0209dd7ff4158a7b04e6a7efa9/Client/Writes/PointData.cs#L394

According to specification of LineProtocol unsigned integers shall be followed by 'u' suffix instead of 'i' https://docs.influxdata.com/influxdb/v2.0/reference/syntax/line-protocol/#uinteger
