### ISSUE TITLE
Connectivity Issue to Influx from Azure Cloud service. Error: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by mariana-gendler** [influxdata/influxdb-client-csharp#162]
Hi,
We are having issues establishing a connection to Influx from a cloud service deployed in Microsoft Azure via the Influx.Client C# library.
When trying to send a request to the WriteApi, receiving the following error:

```
Type : InfluxDB.Client.Core.Exceptions.HttpException, InfluxDB.Client.Core, Version=1.14.0.0, Culture=neutral, PublicKeyToken=2ffdb0e6ebde0d3f
		Message : The request was aborted: Could not create SSL/TLS secure channel.
		Source : InfluxDB.Client
		Help link : 
		ErrorBody : {}
		RetryAfter : 
		Code : 0
		Status : 0
		Data : System.Collections.ListDictionaryInternal
		TargetSite : Void MoveNext()
		HResult : -2146233088
		Stack Trace :    at InfluxDB.Client.Api.Service.WriteService.<PostWriteAsyncWithIRestResponse>d__21.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at InfluxDB.Client.Api.Service.WriteService.<PostWriteAsyncWithHttpInfo>d__20.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at InfluxDB.Client.Api.Service.WriteService.<PostWriteAsync>d__19.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at InfluxDB.Client.WriteApiAsync.<WriteData>d__23.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at InfluxDB.Client.WriteApiAsync.<WritePointsAsync>d__14.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
		   at SE.OIP.Common.Repository.InfluxDB.BulkWriteInfluxRepository`1.<BulkInsertAsync>d__14.MoveNext()
```

I'm setting the following security settings on the service level:

System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;

This seems to be helping while running the service locally(not in Azure), but the error reproduces while running the service in the cloud.
I could not find any specific security settings/options available to set specifically on the "InfluxDBClient".

Please advise.
Thanks,
Mariana

**Comment by bednar** [comment]
Hi @mariana-gendler,

Currently we don’t have a particular settings for the security.

Did you set `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;` before the first request to InfluxDB? According to https://github.com/restsharp/RestSharp/issues/1127 that should be enough.

If you use `.NET Framework 4.6 - 4.6.2 ` please take a look at  - https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#for-net-framework-46---462-and-not-wcf

How your deployment looks like? Do you have authorization proxy before the InfluxDB?

Regards

**Comment by mariana-gendler** [comment]
@bednar ,
The `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;` is set when the service starts before any calls to Influx.
The target .NET version of the service is 4.6.1.
I reviewed the link that you mentioned, as they explain security settings may be set via switches or via code so the setting we set it code should override that in any case.

The service is running on top of an Azure cloud service. We do not set any proxy settings in the service.

**Comment by mariana-gendler** [comment]
@bednar ,
After some further investigation, I found that this issue does not reproduce after upgrading the underlying OS of the cloud service from "Windows Server 2012 R2" to "Windows Server 2016". 
Looks like this is an issue of the OS where in the previous version, it overrides the TLS settings that we set by the service.

Thanks for looking into it!
Closing the issue.
