### ISSUE TITLE
Could not load file or assembly Microsoft.Extensions.ObjectPool Version 5.0.0.0

### ISSUE THREAD

**Issue by scorpionofwar** [influxdata/influxdb-client-csharp#200]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create new C# Project
2. Install InfluxDB Client 17.0 / 18.0
3. Write to Influx2 with the Sync WriteApi

__Expected behavior:__
In version 1.14 it would write to the Influx2 DB without any problems but now it does not work anymore.

__Actual behavior:__
Since I updated to version 17 / 18 the write api does not write anymore. I get the following error on the first try to write to influx:
```
The unhandled exception occurs: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.ObjectPool, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Extensions.ObjectPool, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at InfluxDB.Client.WriteApi.<>c.<.ctor>b__9_3(IGroupedObservable`2 grouped)
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 39

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Extensions.ObjectPool, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
 (Fully-specified)
LOG: Appbase = file:///C:/[...]/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : InfluxDB.Client, Version=1.18.0.0, Culture=neutral, PublicKeyToken=2ffdb0e6ebde0d3f.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\[...]\bin\Debug\werusys.wi5.queue.app.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.Extensions.ObjectPool, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
LOG: Attempting download of new URL file:///C:/[...]/bin/Debug/Microsoft.Extensions.ObjectPool.DLL.
LOG: Attempting download of new URL file:///C:/[...]/bin/Debug/Microsoft.Extensions.ObjectPool/Microsoft.Extensions.ObjectPool.DLL.
LOG: Attempting download of new URL file:///C:/[...]/bin/Debug/Microsoft.Extensions.ObjectPool.EXE.
LOG: Attempting download of new URL file:///C:/[...]/bin/Debug/Microsoft.Extensions.ObjectPool/Microsoft.Extensions.ObjectPool.EXE.
```

The Error occurs after running the following Code, neither the commented code nor the other one is working:
```
[...]
InfluxDBClientOptions options = new InfluxDBClientOptions.Builder()
                .AuthenticateToken(_influxToken)
                .Url(_influxHost)
                .TimeOut(TimeSpan.FromSeconds(300))
                .Build();
_client = InfluxDBClientFactory.Create(options);
_writeApi = _client.GetWriteApi();
[...]
//InfluxProcessValue wi5value = new InfluxProcessValue
//{
//    UtcTimestamp = utcDate,
//    TagName = tagName,
//    Value = (double)value,
//};

try
{
    var point = PointData.Measurement("Berlin")
        .Tag("TagName", tagName)
        .Field("value", (double)value)
        .Timestamp(utcDate, WritePrecision.Ns);

    _writeApi.WritePoint(_databaseName, _influxOrg, point);
    //_writeApi.WriteMeasurement(_databaseName, _influxOrg, WritePrecision.Ns, wi5value);
} 
[...]
```

I already tried to downgrade the dependency to Version 5.0.0, but then the Influx Client also gets downgraded to Version 16.0.0.
On Version 14.0.0 - 16.0.0 this error occurs at the same location in the code:
```
The batch item wasn't processed successfully because: System.MissingMethodException: Method not found: 'Boolean Newtonsoft.Json.Linq.JObject.ContainsKey(System.String)'.
   at InfluxDB.Client.WriteApi.<>c__DisplayClass9_2.<.ctor>b__21(RetryAttempt attempt)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\SelectMany.cs:line 865
``` 
               
__Specifications:__
 - Client Version: 1.18.0.0
 - InfluxDB Version: 2.0.0
 - Platform: Windows 10 Pro

**Comment by bednar** [comment]
Hi @scorpionofwar,

thanks for using our client.

I've tested the `1.18.0` version with following code and everything works fine:

```console
dotnet --version
> 5.0.200
dotnet new console  
dotnet add package InfluxDB.Client --version 1.18.0
dotnet run
```

```csharp
using System;
using System.Diagnostics;
using InfluxDB.Client;
using InfluxDB.Client.Api.Domain;
using InfluxDB.Client.Core;
using InfluxDB.Client.Writes;

namespace test_csharp_client
{
    class Program
    {
        static void Main(string[] args)
        {
            // initialize trace logging
            Trace.Listeners.Add(new TextWriterTraceListener(Console.Out));
            
            // credentials
            const string url = "http://localhost:8086";
            const string token = "my-token";
            const string bucket = "my-bucket";
            const string organization = "my-org";
            
            // values
            const string tag = "tag-value";
            const double value = 86.0;
            var time = DateTime.UtcNow.AddDays(-1);
            
            Console.WriteLine("Initialize client...");
            var options = new InfluxDBClientOptions.Builder()
                .AuthenticateToken(token)
                .Url(url)
                .TimeOut(TimeSpan.FromSeconds(300))
                .Build();
            var client = InfluxDBClientFactory.Create(options);
            client.SetLogLevel(LogLevel.Body);

            using (var writeApi = client.GetWriteApi())
            {
                var point = PointData.Measurement("Berlin")
                    .Tag("TagName", tag)
                    .Field("value", (double)value)
                    .Timestamp(time, WritePrecision.Ns);

                Console.WriteLine("Write data...");
                writeApi.WritePoint(bucket, organization, point);
                
            }
            
            Console.WriteLine("Dispose data...");
            client.Dispose();
        }
    }
}
```

Try to clean your solution by: `dotnet clean` or check if is there a dependency conflict by: `dotnet list package --verbosity detailed`.

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.

**Comment by takczyowak** [comment]
I've encountered similar issue for 4.3.0 version. I've noticed that referenced dll version is not the same version of dll that we can get from referenced assemblies:

![image](https://user-images.githubusercontent.com/59870864/178990967-43a87de1-c227-465f-adac-6084b33b4ea1.png)
