### ISSUE TITLE
Object of type 'System.Double' cannot be converted to type 'System.Decimal'.

### ISSUE THREAD

**Issue by tbluesky2012** [influxdata/influxdb-client-csharp#227]
My InfluxDB.Client version is 1.16, when I debug the code, an error occurs as the following:
   at InfluxDB.Client.Core.Internal.AbstractQueryClient.<>c.<.cctor>b__19_1(Exception e)
   at InfluxDB.Client.Core.Internal.AbstractQueryClient.<Query>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxDB.Client.Core.Internal.AbstractQueryClient.<Query>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxDB.Client.QueryApi.<QueryAsync>d__62.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxDB.Client.QueryApi.<QueryAsync>d__11`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxDB.Client.QueryApi.<QueryAsync>d__9`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by bednar** [comment]
Hi @tbluesky2012,

thanks for using our client. Can you share the full stacktrace and debug output? 

You can enable `debug` output by:

```c#
client.SetLogLevel(LogLevel.Body)
```

Regards

**Comment by tbluesky2012** [comment]
Hi,
Thanks for your&nbsp;reply. When I read the document(v0.88.0), I found that this error had been fixed. And I&nbsp; have rolved this problem by&nbsp;upgrading to the&nbsp; 1.15.0 version of&nbsp; influxdb-client.
With best wishes to you!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "influxdata/influxdb-client-csharp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月12日(星期四) 晚上7:01
***@***.***&gt;;
抄送:&nbsp;"Blue ***@***.******@***.***&gt;;
主题:&nbsp;Re: [influxdata/influxdb-client-csharp] Object of type 'System.Double' cannot be converted to type 'System.Decimal'. (#227)





 
Hi @tbluesky2012,
 
thanks for using our client. Can you share the full stacktrace and debug output?
 
You can enable debug output by:
 client.SetLogLevel(LogLevel.Body)
 
Regards
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
