### ISSUE TITLE
Use HTTP endpoint correctly, or simply get me the tag values

### ISSUE THREAD

**Issue by chris-rutkowski** [influxdata/influxdb-client-csharp#234]
Hello,
I just want tag values of my measurement. Grafana does it with the query `SHOW TAG VALUES FROM "ActAction" WITH KEY=action`. Postman can handle it as well. But the C# client complains about Flux api.

__Steps to reproduce:__
```
var client = InfluxDBClientFactory.CreateV1(_settings.Server, _settings.User, _settings.Password.ToCharArray(), _settings.Bucket, "autogen");
var query = await client.GetQueryApi().QueryRawAsync("SHOW TAG VALUES FROM \"ActAction\" WITH KEY=action");
_logger.LogInformation(query);
client.Dispose();
```

__Expected behavior:__
Same result as I see using HTTPS with Postman
https://example.com/query?db=MYDB&q=SHOW TAG VALUES FROM "ActAction" WITH KEY=action

```
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "ActAction",
                    "columns": [
                        "key",
                        "value"
                    ],
                    "values": [
                        [
                            "action",
                            "turn off"
                        ],
                        [
                            "action",
                            "turn on"
                        ],
                        [
                            "action",
                            "break"
                        ],
                        [
                            "action",
                            "repair"
                        ]
                    ]
                }
            ]
        }
    ]
}
```

__Actual behavior:__
```
[ERR] 08/27/2021 10:20:17 +07:00 [Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware] An unhandled exception has occurred while executing the request.
InfluxDB.Client.Core.Exceptions.ForbiddenException: Flux query service disabled. Verify flux-enabled=true in the [http] section of the InfluxDB config.

   at InfluxDB.Client.Core.Internal.AbstractQueryClient.<>c.<.cctor>b__22_1(Exception e)
   at InfluxDB.Client.Core.Internal.AbstractQueryClient.Query(RestRequest query, Action`2 consumer, Action`1 onError, Action onComplete)
   at InfluxDB.Client.QueryApi.QueryRawAsync(Query query, String org)
   at CNPrivateServer.InfluxService.Values(String measurement, String tag) in /Users/chris/Developer/GitHub/CNPrivate/CNPrivateServer/InfluxService.cs:line 45
   at CNPrivateServer.Controller.GetActions() in /Users/chris/Developer/GitHub/CNPrivate/CNPrivateServer/Controller.cs:line 50
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

__Specifications:__
 - Client Version: 1.19
 - InfluxDB Version: 1.8
 - Platform: Ubuntu 20.04

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
