### ISSUE TITLE
unsupported binary expression

### ISSUE THREAD

**Issue by weiwxg** [influxdata/influxdb-client-csharp#235]
i stored data with poco : 
```csharp
public class DataEntity
{
    public long StartWithTicks { get; set; }
    public long EndWithTicks { get; set; }
}
```

when i query data use linq as bellow

```csharp
var client = await GetDbClientAsync();
var query = from s in InfluxDBQueryable<GanttChart.GanttChart>.Queryable("bucket", "org", client.GetQueryApiSync())
            where s.EndWithTicks <= 637656739543829486
            select s;
```

it throw runtime error

```
runtime error @3:188-3:309: filter: cannot compile @ 3:199-3:308: unsupported binary expression int <= string
InfluxDB.Client.Core.Exceptions.BadRequestException: runtime error @3:188-3:309: filter: cannot compile @ 3:199-3:308: unsupported binary expression int <= string
   at InfluxDB.Client.Core.Internal.AbstractQueryClient.<>c.<.cctor>b__22_1(Exception e)
   at InfluxDB.Client.Core.Internal.AbstractQueryClient.QuerySync(RestRequest query, Action`2 consumer, Action`1 onError, Action onComplete)
   at InfluxDB.Client.Core.Internal.AbstractQueryClient.QuerySync(RestRequest query, IFluxResponseConsumer responseConsumer, Action`1 onError, Action onComplete)
   at InfluxDB.Client.QueryApiSync.QuerySync[T](Query query, String org)
   at InfluxDB.Client.Linq.Internal.InfluxDBQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
   at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at System.Linq.Dynamic.Core.DynamicEnumerableExtensions.CastToList[T](IEnumerable source)
   at System.Linq.Dynamic.Core.DynamicEnumerableAsyncExtensions.<>c__DisplayClass7_0`1.<CastToListAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by weiwxg** [comment]
![image](https://user-images.githubusercontent.com/24971860/131199231-d3ca83f2-6af0-4d03-94c7-7bd1a7b11902.png)

I think the `EndWithTicks` is stored as a `long` correctly.  Stangely, if i define the `EndWithTicks` as a  `float` property, it can get query result

**Comment by bednar** [comment]
@weiwxg, thanks for your detail investigation. The problem is caused by our mapping function between LINQ and Flux AST.

I have prepared a fixed version within #236. Development version of the client will be available after #236 acceptance, stable version in regular release cycle.

**Comment by weiwxg** [comment]
Thanks for your reply! And another question is how to filter with measurement? As i can see from document, we can define `Converter` pass into `GetQueryApiSync( )`. What i'm wondering is Whether its filter in memory or not?

**Comment by bednar** [comment]
> Thanks for your reply! And another question is how to filter with measurement?

The LINQ provider doesn't supports to filtering by measurement.

> What i'm wondered is Whether it filtered in memory or not?

The library attempts to evaluate a query on the server as much as possible. For more info see - https://github.com/influxdata/influxdb-client-csharp/blob/466c9fe8ff16d9f9ef3c9b1a83b4d1c275f34f6b/Client.Linq/README.md#client-side-evaluation
