### ISSUE TITLE
CreateBucketAsync() throws an "failed to unmarshal json: id must have a length of 16 bytes" exception

### ISSUE THREAD

**Issue by bryanmillerph** [influxdata/influxdb-client-csharp#245]
__Steps to reproduce:__

I was just following the instructions on how to create a bucket (**url and token are valid in my tests**):

```
var influxDBClient = InfluxDBClientFactory.Create("http://localhost:8086", Token);
var retention = new BucketRetentionRules(BucketRetentionRules.TypeEnum.Expire, 3600);
var bucket = await influxDBClient.GetBucketsApi().CreateBucketAsync("iot_bucket", retention, "org_id");
```
            
__Expected behavior:__
Bucket is created on influxdb

__Actual behavior:__
An exception was thrown with message **failed to unmarshal json: id must have a length of 16 bytes**
This error occurs with or without the BucketRetentionRules parameter to CreateBucketAsync()

__Stack Trace:__

   at InfluxDB.Client.Api.Service.BucketsService.<PostBucketsAsyncWithIRestResponse>d__109.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at InfluxDB.Client.Api.Service.BucketsService.<PostBucketsAsyncWithHttpInfo>d__108.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at InfluxDB.Client.Api.Service.BucketsService.<PostBucketsAsync>d__107.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

__Specifications:__
 - Client Version: 3.0.0
 - InfluxDB Version: 2.0.8 (running in docker container)
 - Platform: .NET5, Windows 10

**Comment by bryanmillerph** [comment]
Thank you, I can confirm that this is working!

**One thing to note, maybe this will help someone in the future, in order to get any data from FindOrganizationsAsync(), the InfluxDB Token must be "All Access Token"**
