### ISSUE TITLE
InfluxDB.Client.Core.Exceptions.NotFoundException when trying to delete a measurement

### ISSUE THREAD

**Issue by micuentadecasa** [influxdata/influxdb-client-csharp#284]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

I create a C# code to try to delete a measurement

        const string database = "telegraf";
        const string retentionPolicy = "autogen";
        const string measurement = "camerasAndModelsRecords";

        var client = InfluxDBClientFactory.CreateV1("http://localhost:8086",
                   "telegraf",
                   "telegraf".ToCharArray(),
                   database,
                   retentionPolicy);

        var dApi = client.GetDeleteApi();
        var start = new DateTime(2018, 1, 1).ToUniversalTime();
        var stop = new DateTime(2023, 1, 1).ToUniversalTime();
        await client.GetDeleteApi().Delete(start, stop, measurement, database, "my_org");
        Console.WriteLine("deleted measurement ..");

I don't have any problem inserting or getting data using your client library, but I'm not able to use the delete API.

__Expected behavior:__
Describe what you expected to happen.

Deleted measurement

__Actual behavior:__
Describe What actually happened.

An exception of type 'InfluxDB.Client.Core.Exceptions.NotFoundException' occurred in System.Private.CoreLib.dll but was not handled in user code: '404 page not found'

at InfluxDB.Client.Api.Service.DeleteService.<PostDeleteAsyncWithIRestResponse>d__21.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at InfluxDB.Client.Api.Service.DeleteService.<PostDeleteAsyncWithHttpInfo>d__20.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at influxWrapper.<deleteCamerasInDatabase>d__3.MoveNext() in [/home/luis/projects/avatesting/src/edge/modules/cronmodule/influxWrapper.cs]():line 181
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at cronmodule.Program.<Main>d__1.MoveNext() in [/home/luis/projects/avatesting/src/edge/modules/cronmodule/Program.cs]():line 54

__Specifications:__
 - Client Version: 3.4.0-dev.4986
 - InfluxDB Version: 1.8
 - Platform: linux

**Comment by bednar** [comment]
Hi @micuentadecasa,

thanks for using our client.

> An exception of type 'InfluxDB.Client.Core.Exceptions.NotFoundException' occurred in System.Private.CoreLib.dll but was not handled in user code: '404 page not found'
> InfluxDB Version: 1.8

The InfluxDB 1.8 doesn't supports delete data via `/api/v2/delete` endpoint. This client uses  compatibility APIs for connection to InfluxDB 1.8. For more info see https://github.com/influxdata/influxdb-client-csharp#influxdb-18-api-compatibility.

Regards

**Comment by micuentadecasa** [comment]
Thanks @bednar , just one thing before closing this, how can I delete in the v 1.8?

**Comment by bednar** [comment]
You have to connect to database and use `database`. For more info see https://docs.influxdata.com/influxdb/v1.8/query_language/manage-database/#delete-series-with-delete
